backend/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import ObtainAuthToken


from .views import (
    marca,
    producto,
    dashboard,
    imagen_producto,
    punto_imagen,
    herramientas,
    usuarios,
    operativos,
    REST_view,
    informes
)


router = routers.DefaultRouter()
router.register(r'operativoconnection', REST_view.OperativoSerializerViewSet)
router.register(r'operativo', REST_view.OperativoViewSet)
router.register(r'users', REST_view.UserViewSet)
router.register(r'brands', REST_view.BrandViewSet, basename='Brand')
router.register(r'product', REST_view.ProductViewSet)
router.register(r'productbybrand', REST_view.ProductList)
router.register(r'imageproduct', REST_view.ImageDetailProduct)
router.register(r'detailproduct', REST_view.DetailImageProductViewSet)
router.register(r'markerproduct', REST_view.DetailMarkerProduct)
router.register(r'categories_brand', REST_view.CategoryBrandViewSet)
router.register(r'categories_product', REST_view.CategoryProductViewSet)
#router.register(r'logout', REST_view.Logout, basename='Logout')

urlpatterns = [
    path('', dashboard.index, name='index'),
    path('marcas/', marca.marcas, name='marcas'),
    path('marcas/nuevo', marca.brand_new, name='brand_new'),
    path('marcas/editar/<int:pk>', marca.brand_edit, name='brand_edit'),
    path('marcas/<int:pk>/eliminar/', marca.brand_delete, name='brand_delete'),
    path('marcas/<int:pk>/productos/', marca.products_by_brand, name='products_by_brand'),

    path('productos', producto.productos, name='productos'),

    path('producto/<int:pk_brand>/new', producto.product_new, name='product_new'),
    path('producto/<int:pk>', producto.product_detail, name='product_detail'),
    path('producto/<int:pk>/delete/', producto.product_delete, name='product_delete'),

    path('producto/<int:pk>/imagen/new', imagen_producto.new, name="image_producto_new"),
    path('producto/<int:pk>/imagen/<int:pk_image_product>', imagen_producto.detail, name="image_producto_detail"),
    path('producto/<int:pk>/imagen/<int:pk_image_product>/delete/', imagen_producto.delete, name="image_producto_delete"),

    path('producto/<int:pk_product>/imagen/<int:pk_image_product>/punto/new', punto_imagen.new, name="punto_imagen_new"),
    path('producto/<int:pk_product>/imagen/<int:pk_image_product>/punto/<int:pk>', punto_imagen.detail, name="punto_imagen_detail"),
    path('producto/<int:pk_product>/imagen/<int:pk_image_product>/punto/<int:pk>/delete/', punto_imagen.delete, name="punto_imagen_delete"),

    path('producto/<int:pk_product>/imagen/<int:pk_image_product>/<int:pk_mark>/detalle/', punto_imagen.image_pointer, name="punto_detail_imagen"),
    path('producto/<int:pk_product>/imagen/<int:pk_image_product>/<int:pk_mark>/detalle/new', punto_imagen.new_image, name="punto_detail_imagen_new"),
    path('producto/<int:pk_product>/imagen/<int:pk_image_product>/detalle/<int:pk_mark>/<int:pk>', punto_imagen.image_detail, name="punto_detail_imagen_detail"),
    path('producto/<int:pk_product>/imagen/<int:pk_image_product>/detalle/<int:pk_mark>/delete/<int:pk>', punto_imagen.delete_detail, name="punto_detail_imagen_delete"),

    path('herramientas/', herramientas.index, name="herramientas"),
    path('herramientas/brand/categorias/', herramientas.categoria_marca, name="category_brand"),
    path('herramientas/brand/categoria/new', herramientas.create_categoria_marca, name="new_category_brand"),
    path('herramientas/brand/categoria/<int:pk>', herramientas.categoria_marca_detail, name="detail_category_brand"),
    path('herramientas/brand/categoria/<int:pk>/delete', herramientas.categoria_marca_delete, name="categoria_marca_delete"),

    path('herramientas/producto/categorias/', herramientas.categoria_producto, name="category_producto"),
    path('herramientas/producto/categoria/new', herramientas.create_categoria_producto, name="new_category_producto"),
    path('herramientas/producto/categoria/<int:pk>', herramientas.categoria_producto_detail, name="detail_category_producto"),
    path('herramientas/producto/categoria/<int:pk>/delete', herramientas.categoria_producto_delete, name="categoria_producto_delete"),

    path('usuarios/', usuarios.index, name="list_usuarios"),
    path('usuarios/new', usuarios.create, name="create_usuarios"),
    path('usuarios/<int:pk>', usuarios.detail, name="detail_usuarios"),

    path('operativos/', operativos.index, name="operativos"),
    path('operativos/new', operativos.new, name="new_operativo"),
    path('operativos/view/<int:pk>', operativos.view, name="view_operativo"),
    path('operativos/<int:pk>', operativos.operativo_edit, name="detail_operativo"),
    path('operativos/invalidate/<int:pk>', operativos.invalidate, name="invalidate_operativo"),
    path('operativos/activate/<int:pk>', operativos.activate, name="activate_operativo"),
    path('operativos/chat/<int:pk>', operativos.chat, name="chat_operativo"),
    path('operativos/brand_chat/<int:pk>', operativos.chat_marca, name="chat_marca"),
    path('externalchat/<int:pk>', operativos.chat_ext_marca, name="chat_ext_marca"),
    path('operativos/connetions/<int:pk>', operativos.list_connections, name="connections"),
    path('operativos/disconnect/<int:pk>/<int:tk>', operativos.disconnect_session, name="disconnect"),
    

    path('informes', informes.index, name="informes"),
    path('informes/operativos', informes.operativos, name="informe_operativo"),
    path('informes/operativos/<int:pk>/chat', informes.chat, name="chat_informe"),

    path('', include(router.urls)),

    path('login_app/', REST_view.login_app, name="login_app"),
    path('logout/', REST_view.Logout.as_view(), name="logout"),
    path('token_chat/', REST_view.chat_token, name="chat_token"),
    path('auth/', ObtainAuthToken.as_view()),
    path('opertivos_list/', operativos.OperativoList.as_view(), name="list_operativo")

]

brands/urls.py
""" Agatha brands URLs """
# Django
from django.urls import path

#views
from brands import views 

urlpatterns = [
    # URLs admin brands
    path(#Lista de marcas
        route='', 
        view= views.brands, 
        name='list'),
    path(# Nueva marca
        route='nuevo', 
        view= views.brand_new, 
        name='new'),
    path(# Edicion de marca
        route='editar/<int:pk>', 
        view= views.brand_edit, 
        name='edit'),
    path(# delete marca
        route='<int:pk>/eliminar/', 
        view= views.brand_delete, 
        name='delete'),
    path(# productos marca
        route = 'productos/<int:pk>',
        view = views.products_by_brand,
        name = 'products'
    ),

    # URLs admin brands category 
    path(
        route = 'categorias',
        view = views.brand_category,
        name="brand_category"
    ),
    path(
        route = 'nueva_categoria',
        view = views.new_brand_category, 
        name="new_brand_category"
    ),
    path(
        route = 'categoria/<int:pk>', 
        view = views.detail_brand_category, 
        name="detail_brand_category"
    ),
    path(
        route = 'categoria/<int:pk>/eliminar', 
        view = views.delete_brand_category, 
        name="delete_brand_category"
    ),
]

pirateshield/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda req: redirect('/agatha/accounts/login')),
	path('backend/', include('backend.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/models.py
from django.db import models
from django.utils.safestring import mark_safe
from django.contrib.auth.models import AbstractUser
from ckeditor.fields import RichTextField

# Create your models here.

class CategoryBrand(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categorias de marca"


class CategoryProduct(models.Model):
    name = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categorias de producto"


class Brand(models.Model):
    name = models.CharField(max_length=250)
    logo = models.ImageField(
        upload_to='clients/', default='clients/logo_default.jpg')

    banner = models.ImageField(
        upload_to='clients/', default='clients/logo_default.jpg')

    description = models.TextField()
    brand_category_id = models.ForeignKey(
        CategoryBrand, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Marcas"


class Product(models.Model):
    name = models.CharField(max_length=250)
    reference = models.CharField(max_length=250)
    brand = models.ForeignKey(Brand, on_delete=models.DO_NOTHING, related_name='products')
    description = models.TextField(null=True)
    image = models.ImageField(
        upload_to='clients/', default='clients/logo_default.jpg')

    product_category = models.ForeignKey(
        CategoryProduct, on_delete=models.DO_NOTHING)

    created = models.DateTimeField(auto_now=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Productos"


class ImageProduct(models.Model):
    name = models.CharField(max_length=250)
    image = models.ImageField(
        upload_to='products/', default='products/image_default.jpg')

    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)

    def image_tag(self):
        return mark_safe(
            '<a href="/media/{0}"><img src="/media/{0}"></a>'
            .format(self.image))

    def get_create_deatail(self):
        return mark_safe(
            '<a class="related-widget-wrapper-link add-related" \
             href="/admin/backend/detailimageproduct/add/ \
             ?_to_field=id&_popup=1&image_product={0}&url_image=/media/{1}"> \
             Agregar</a>'.format(self.id, self.image))

    image_tag.short_description = 'Image of product'
    image_tag.allow_tags = True

    get_create_deatail.short_description = 'Detalle'
    get_create_deatail.allow_tags = True

    def __str__(self):
        return self.name


class DetailImageProduct(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    marker_x = models.FloatField()
    marker_y = models.FloatField()
    image_check = models.ImageField(
        upload_to='products/details',
        default='products/details/image_default.jpg')

    image_fail = models.ImageField(
        upload_to='products/details',
        default='products/details/image_default.jpg')
    image_product = models.ForeignKey(ImageProduct, on_delete=models.CASCADE)

    def get_image_product(self):
        return mark_safe('<div class="select-point">' + self.image_product.image_tag() + '</div>')

    get_image_product.short_description = 'Image of product'
    get_image_product.allow_tags = True

    class Meta:
        verbose_name_plural = "Marcadores de Detalles"

    def __str__(self):
        return self.name

class ImageDetailCompare(models.Model):
    TYPE_CHOICES = (
        ('1', 'Imagen Correcta'),
        ('2', 'Imagen Incorrecta'),
    )

    name = models.CharField(max_length=250, blank=True, null=True)
    description = RichTextField(blank=True, null=True)
    image_check = models.ImageField(upload_to='products/details', blank=True)
    image_fail = models.ImageField(upload_to='products/details', blank=True)
    detail_image = models.ForeignKey(
        DetailImageProduct, on_delete=models.CASCADE, blank=True, null=True)


class User(AbstractUser):
    brand = models.ForeignKey(
        Brand, on_delete=models.DO_NOTHING, blank=True, null=True)

    image = models.ImageField(
        upload_to='users/',
        default='users/default-avatar.png', blank=True, null=True)

    movil = models.CharField(max_length=10, blank=True, null=True)
    is_user_token = models.BooleanField(default=False)


class UserBrand(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)


class Operativo(models.Model):
    token = models.CharField(max_length=250)
    token_chat = models.CharField(max_length=250, blank=True)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    expiration = models.DateTimeField()
    name = models.CharField(max_length=250, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    connections = models.IntegerField(blank=True, null=True)
    first_login = models.DateTimeField(blank=True, null=True)
    last_login = models.DateTimeField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    is_ready = models.BooleanField(default=False)
    activation = models.DateTimeField(blank=True, null=True)
    brandsList = models.CharField(max_length=250, blank=True, null=True)
    productList = models.CharField(max_length=250, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)
    close_observation = RichTextField(blank=True, null=True)


class OperativoBrand(models.Model):
    operativo = models.ForeignKey(Operativo, on_delete=models.DO_NOTHING)
    brand = models.ForeignKey(Brand, on_delete=models.DO_NOTHING)
    producto = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    all_prodcut = models.BooleanField()


class OperativoConnection(models.Model):
    name_user = models.CharField(max_length=250, blank=True, null=True)
    ip = models.CharField(max_length=250, blank=True, null=True)
    is_active = models.BooleanField(default=False, null=False)
    operativo = models.ForeignKey(Operativo, on_delete=models.DO_NOTHING)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, default = '0', blank=True, null=True)

backend/views/dashboard.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def index(request):

	print(request.user)
	return render(request, 'dashboard.html', {})
	




	

backend/views/imagen_producto.py
from django.template import loader
from django.http import HttpResponse 
from django.shortcuts import redirect, get_object_or_404

from backend.models import Product, ImageProduct
from backend.forms import ImagenProductForm, DeleteImagenProduct

from pprint import pprint

def new(request, pk):
	template = loader.get_template('imagen_producto/create.html')
	product = get_object_or_404(Product, pk=pk)

	if request.method == 'POST':
		form = ImagenProductForm(request.POST, request.FILES)

		#pprint(request.POST)
	
		if form.is_valid():
			image = form.save(commit=False)
			print(image.image)
			image.product = product
			image.save()

			return redirect('product_detail', pk=pk)
	else:
		form = ImagenProductForm()
	
	return HttpResponse(template.render({'form': form, 'product':pk}, request))



def detail(request, pk, pk_image_product):
	template = loader.get_template('imagen_producto/create.html')
	image_product = get_object_or_404(ImageProduct, pk=pk_image_product)
	marks_product = image_product.detailimageproduct_set.all()

	#pprint(image_product)
	#pprint(marks_product)
	if request.method == 'POST':
		form = ImagenProductForm(request.POST, request.FILES, instance=image_product)

		if form.is_valid():
			image = form.save(commit=False)
			image.save()

			return redirect('product_detail', pk=pk)
	else:
		form = ImagenProductForm(instance=image_product)
	
	return HttpResponse(template.render({'form': form, 'is_edit':'True', 'marks': marks_product, 'product': pk,'image_product': image_product}, request))


def delete(request, pk, pk_image_product):

	template = loader.get_template('imagen_producto/delete.html')
	image_product = get_object_or_404(ImageProduct, pk=pk_image_product)

	if request.method == 'POST':
		form = DeleteImagenProduct(request.POST, instance=image_product)

		if form.is_valid():
			image_product.delete()
			return redirect('product_detail', pk=pk)
	else:
		form = DeleteImagenProduct(instance=image_product)
	
	return HttpResponse(template.render({'form': form, 'image_product':image_product, 'product': pk}, request))

backend/views/send_email.py
from django.template.loader import get_template
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMultiAlternatives
from django.conf import settings


def send_email(template, context, emails):

    template_email = get_template(template)
            
    content = template_email.render(context)
    
    email = EmailMultiAlternatives(
        subject = context['subject'],
        body ='Agatha',
        from_email = settings.EMAIL_HOST_USER,
        to = emails,
    )
            
    email.attach_alternative(content, 'text/html')
    email.send()

backend/views/tools.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    return render(request, 'tools.html')

backend/templates/brands/brand_delete.html
{% extends "layout/base.html" %}


{% block content %}
<div class="title-internal">
	<h2>Eliminar marca</h2>
	<h5>¿Desea borrar la marca: "{{ brand }}"?</h5>
</div>

<div class="grid-x">
	<div class="cell small-12 medium-6">
		<a href="{% url 'brands:list' %}" class="button expanded alert">REGRESAR</a>
	</div>
	<div class="cell small-12 medium-6">
		<form method="POST">
			{% csrf_token %}
			{{ form }}
			<button type="submit" class="button expanded ">ELIMINAR</button>	
		</form>
		
	</div>
</div>

{% endblock %}

backend/templates/brands/brand_form.html
{% extends "layout/base.html" %}


{% block content %}


<form  method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	<h2>
		{{ title }}
	</h2>
	
	{{ form.as_p }}
	
	<div class="grid-x">
		<div class="cell small-12 medium-6">
			<a href="{% url 'brands:list' %}" class="button expanded alert">REGRESAR</a>
		</div>
		<div class="cell small-12 medium-6">
			<input type="submit" class="button expanded" value="GUARDAR">
		</div>
	</div>
</form>
{% endblock %}

backend/templates/brands/brands_list.html
{% extends "layout/base.html" %}
{% block content %}
	
	<nav class="actions-bar grid-x">
		<div class="cell small-12 medium-6">
			<div class="title-actions-bar">Marcas</div>
		</div>
		<div class="cell small-12 medium-6 actions-buttons">
			<a class="button hollow small" href="{% url 'brands:new' %}">Crear marca</a>
		</div>
	</nav>

	{% if brand_list %}
	<ul class="list-data">
		{% for brand in brand_list %}
		<li class="grid-x">
			
			<div class="cell small-8 medium-8">
				<figure>
					<img src="/media/{{ brand.logo }}" alt="">
				</figure>
				<div class="info-row">
					<h3>{{ brand.name }}</h3>		
					<span>{{ brand.category.name }}</span> 
					<span><strong>Productos:</strong> {{ brand.product_set.all|length }}</span>
				</div>	
			</div>
			<div class="cell auto content-buttons">
				<div class="small button-group">
					<a href="{% url 'brands:products' brand.pk  %}" class="button">Ver productos</a>
					<a href="{% url 'brands:edit' pk=brand.pk %}" class="button">Editar</a>
				  	<a href="{% url 'brands:delete' pk=brand.pk %}" class="button alert">Eliminar</a>
				</div>
			</div>
		</li>
		{% endfor %}
	</ul>
	{% endif %}
{% endblock %}

backend/templates/brands/create_category.html
{% extends "layout/base.html" %}


{% block content %}

<form  method="POST" enctype="multipart/form-data">
	<h2>
		{% if is_edit %}
			Editar Categoría
		{% else %}
			Crear Categoría para marcas
		{% endif %}
		
	</h2>

	{% csrf_token %}
	{{ form.as_p }}
	
	<div class="grid-x">
		<div class="cell small-12 medium-6">
			<a href="{% url 'brand:brand_category' %}" class="button expanded alert">REGRESAR</a>
		</div>
		<div class="cell small-12 medium-6">
			<input type="submit" class="button expanded" value="GUARDAR">
		</div>
	</div>
	
	
</form>
{% endblock %}

backend/templates/brands/delete_category.html
{% extends "layout/base.html" %}


{% block content %}
<div class="title-internal">
	<h2>Eliminar categoría</h2>
	<h5>¿Desea borrar la categoría: "{{ brand }}"?</h5>
</div>

<div class="grid-x">
	<div class="cell small-12 medium-6">
		<a href="{% url 'brand:brand_category' %}" class="button expanded alert">REGRESAR</a>
	</div>
	<div class="cell small-12 medium-6">
		<form method="POST">
			{% csrf_token %}
			{{ form }}
			<button type="submit" class="button expanded ">ELIMINAR</button>	
		</form>
		
	</div>
</div>

{% endblock %}

backend/templates/brands/list_category.html
{% extends "layout/base.html" %}
{% block content %}
	
	<nav class="actions-bar grid-x">
		<div class="cell small-12 medium-6">
			<div class="title-actions-bar">Categorias de Marca</div>
		</div>
		<div class="cell small-12 medium-6 actions-buttons">
			<a class="button hollow small" href="{% url 'brand:new_brand_category' %}">Crear categoria de marca</a>
		</div>
	</nav>

	{% if brand_categories %}
	<ul class="list-data single-list">
		{% for item in brand_categories %}
		<li class="grid-x">
			<div class="cell small-8 medium-8">
				<div class="info-row ">
					<h3>{{ item.name }}</h3>		
					<span>{{ item.item_category_id.name }}</span> 
					<span>(Marcas: {{ item.brand_set.all|length }})</span>
				</div>	
			</div>
			<div class="cell auto content-buttons">
				<div class="small button-group">
				  <a href="{% url 'brand:detail_brand_category' pk=item.pk %}" class="button">Editar</a>
				  <a href="{% url 'brand:delete_brand_category' pk=item.pk %}" class="button alert">Eliminar</a>
				</div>
			</div>
		</li>
		{% endfor %}
	</ul>
	{% endif %}
{% endblock %}